#WAP to illustrate String methods
example=input("Enter a string for string methods:")
print(example.upper())
print(example.lower())
nosp=example.strip()
print(nosp)
another=example.replace("i","j")
print(another)
sep=example.split(" ")
print(sep)