firstnum= int(input('Enter the first number\n'));
secondnum= int(input('Enter the second number\n'));
sum=firstnum+secondnum;
difference=firstnum-secondnum;
product=firstnum*secondnum;
power=firstnum**secondnum;
print("\nsum:",sum);
print("\nDifference:",difference);
print("\nProduct:",product);
print("\nPower:",power);