fname="file.txt"
this=open(fname,'r')
print(this.read())
this="/home/nullproj/Documents/BIM-5th-semester/python/file.txt"
fil=open(this,'r')
print(fil.read())
fil.close()
fil=open(this,'a')
fil.write("\nThis is the next line that i wrote using py")
fil.close()
fil=open(this,'r')
print(fil.read())
fil.close()
fil=open(this,'w')
fil.write("I overwrote the file using file handling")
fil.close()
fil=open(this,'r')
print(fil.read())
fil.close()
